#
# ElasticSearch最全详细使用教程：入门、索引管理、映射详解https://cloud.tencent.com/developer/article/1547867
#

# 1. 查看集群的健康状况
GET http://localhost:9200/_cat/
Accept: application/json
###

# 说明：v是用来要求在结果中返回表头
GET http://localhost:9200/_cat/health?v
Accept: application/json
###

# 查看所有索引
GET http://localhost:9200/_cat/indices?v
###

# 创建索引
PUT http://localhost:9200/shopping
###

# 查找索引
GET http://localhost:9200/shopping
###

# 创建文档
POST http://localhost:9200/shopping/phone
Content-Type: application/json

{
  "title":"小米手机",
  "category":"小米",
  "images":"http://www.gulixueyuan.com/xm.jpg",
  "price":3999.00

}
###

# 查找文档，indeies/_doc/id
GET http://localhost:9200/shopping/_doc/z94hunoBUNkCo_FEjBuh
###

# 创建文档
POST http://localhost:9200/shopping/phone/z94hunoBUNkCo_FEjBuh
Content-Type: application/json

{
  "title":"小米手机",
  "category":"小米",
  "images":"http://www.gulixueyuan.com/xm.jpg",
  "price": 1999.00
}
###

# 更新字段，index/_update/id
POST http://localhost:9200/shopping/_update/z94hunoBUNkCo_FEjBuh
Content-Type: application/json

{
  "doc": {
    "title":"华为手机",
    "category":"华为"
  }
}
###



### 删除索引
DELETE http://localhost:9200/xxx
###

# 获取指定索引
GET http://localhost:9200/megacorp/
Accept: application/json

### 新建一个megacorp索引，类型为employee，1为ID
PUT http://localhost:9200/megacorp/employee/1?pretty
Content-Type: application/json

{
  "first_name" : "Niko",
  "last_name" :  "Zhang",
  "age" :        25,
  "about" :      "I love to go rock climbing",
  "interests": [ "photograph", "code" ]
}
###


###
GET http://localhost:9200/_count?pretty -d
###
